//
// build.gradle in TeamCode
//
// Most of the definitions for building your module reside in a common, shared
// file 'build.common.gradle'. Being factored in this way makes it easier to
// integrate updates to the FTC into your code. If you really need to customize
// the build definitions, you can place those customizations in this file, but
// please think carefully as to whether such customizations are really necessary
// before doing so.

import org.gradle.external.javadoc.JavadocMemberLevel


// Custom definitions may go here

// Include common definitions from above.
apply from: '../build.common.gradle'
apply from: '../build.dependencies.gradle'

android {
    namespace = 'org.firstinspires.ftc.teamcode'

    packagingOptions {
        jniLibs.useLegacyPackaging true
    }
}

dependencies {
    implementation project(':FtcRobotController')

    testImplementation 'junit:junit:4.13.2'
}

def phoenixAndroidComponents = androidComponents
phoenixAndroidComponents.onVariants(
        phoenixAndroidComponents.selector().withName('debug')) { variant ->
    tasks.register('phoenixJavadocs', Javadoc) {
        group = 'documentation'
        description = 'Generates strict API documentation for the Phoenix framework.'

        source(variant.sources.java.all)
        include('edu/ftcphoenix/fw/**/*.java')
        classpath = files(
                variant.compileClasspath,
                phoenixAndroidComponents.sdkComponents.bootClasspath)
        destinationDir = rootProject.layout.buildDirectory.dir('docs-site/api').get().asFile
        failOnError = true

        options.memberLevel = JavadocMemberLevel.PROTECTED
        options.encoding = 'UTF-8'
        options.charSet = 'UTF-8'
        options.docEncoding = 'UTF-8'
        options.windowTitle = 'Phoenix Framework API'
        options.docTitle = 'Phoenix Framework API'
        options.noTimestamp = true
        options.addBooleanOption('Xdoclint:all,-missing', true)
        options.addBooleanOption('Werror', true)
    }
}
